name: License Check

on:
  push:
    paths:
      - 'requirements*.txt'
  pull_request:
    paths:
      - 'requirements*.txt'

permissions:
  contents: read

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install pip-licenses -r requirements.txt
      - name: Check licenses
        run: |
          pip-licenses --order=license --format=markdown
          pip-licenses \
            --fail-on="GNU General Public License v2" \
            --fail-on="GNU General Public License v3" \
            --fail-on="GNU Affero General Public License v3" \
            --fail-on="Server Side Public License" \
            --fail-on="GNU Lesser General Public License v2" \
            --fail-on="GNU Lesser General Public License v3"
